// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dlogger.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_LOGGINGMODULE_DLOGGER_H_
#define _FAST_DDS_GENERATED_LOGGINGMODULE_DLOGGER_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DLOGGER_SOURCE)
#define DLOGGER_DllAPI __declspec( dllexport )
#else
#define DLOGGER_DllAPI __declspec( dllimport )
#endif // DLOGGER_SOURCE
#else
#define DLOGGER_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DLOGGER_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace LoggingModule {

/*!
 * @brief This class represents the enumeration DL_Kind defined by the user in the IDL file.
 * @ingroup dlogger
 */
enum DL_Kind : uint32_t
{
    Error,
    Warning,
    Info,
    Notice,
    Debug
};


/*!
 * @brief This class represents the structure DL_Context defined by the user in the IDL file.
 * @ingroup dlogger
 */
class DL_Context
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DL_Context();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DL_Context();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LoggingModule::DL_Context that will be copied.
     */
    eProsima_user_DllExport DL_Context(
            const DL_Context& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LoggingModule::DL_Context that will be copied.
     */
    eProsima_user_DllExport DL_Context(
            DL_Context&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LoggingModule::DL_Context that will be copied.
     */
    eProsima_user_DllExport DL_Context& operator =(
            const DL_Context& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LoggingModule::DL_Context that will be copied.
     */
    eProsima_user_DllExport DL_Context& operator =(
            DL_Context&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x LoggingModule::DL_Context object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DL_Context& x) const;

    /*!
     * @brief Comparison operator.
     * @param x LoggingModule::DL_Context object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DL_Context& x) const;

    /*!
     * @brief This function copies the value in member filename
     * @param _filename New value to be copied in member filename
     */
    eProsima_user_DllExport void filename(
            const std::string& _filename);

    /*!
     * @brief This function moves the value in member filename
     * @param _filename New value to be moved in member filename
     */
    eProsima_user_DllExport void filename(
            std::string&& _filename);

    /*!
     * @brief This function returns a constant reference to member filename
     * @return Constant reference to member filename
     */
    eProsima_user_DllExport const std::string& filename() const;

    /*!
     * @brief This function returns a reference to member filename
     * @return Reference to member filename
     */
    eProsima_user_DllExport std::string& filename();


    /*!
     * @brief This function sets a value in member line
     * @param _line New value for member line
     */
    eProsima_user_DllExport void line(
            int32_t _line);

    /*!
     * @brief This function returns the value of member line
     * @return Value of member line
     */
    eProsima_user_DllExport int32_t line() const;

    /*!
     * @brief This function returns a reference to member line
     * @return Reference to member line
     */
    eProsima_user_DllExport int32_t& line();


    /*!
     * @brief This function copies the value in member function
     * @param _function New value to be copied in member function
     */
    eProsima_user_DllExport void function(
            const std::string& _function);

    /*!
     * @brief This function moves the value in member function
     * @param _function New value to be moved in member function
     */
    eProsima_user_DllExport void function(
            std::string&& _function);

    /*!
     * @brief This function returns a constant reference to member function
     * @return Constant reference to member function
     */
    eProsima_user_DllExport const std::string& function() const;

    /*!
     * @brief This function returns a reference to member function
     * @return Reference to member function
     */
    eProsima_user_DllExport std::string& function();


    /*!
     * @brief This function copies the value in member category
     * @param _category New value to be copied in member category
     */
    eProsima_user_DllExport void category(
            const std::string& _category);

    /*!
     * @brief This function moves the value in member category
     * @param _category New value to be moved in member category
     */
    eProsima_user_DllExport void category(
            std::string&& _category);

    /*!
     * @brief This function returns a constant reference to member category
     * @return Constant reference to member category
     */
    eProsima_user_DllExport const std::string& category() const;

    /*!
     * @brief This function returns a reference to member category
     * @return Reference to member category
     */
    eProsima_user_DllExport std::string& category();

private:

    std::string m_filename;
    int32_t m_line{0};
    std::string m_function;
    std::string m_category;

};


/*!
 * @brief This class represents the structure DL_Entry defined by the user in the IDL file.
 * @ingroup dlogger
 */
class DL_Entry
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DL_Entry();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DL_Entry();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LoggingModule::DL_Entry that will be copied.
     */
    eProsima_user_DllExport DL_Entry(
            const DL_Entry& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LoggingModule::DL_Entry that will be copied.
     */
    eProsima_user_DllExport DL_Entry(
            DL_Entry&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LoggingModule::DL_Entry that will be copied.
     */
    eProsima_user_DllExport DL_Entry& operator =(
            const DL_Entry& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LoggingModule::DL_Entry that will be copied.
     */
    eProsima_user_DllExport DL_Entry& operator =(
            DL_Entry&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x LoggingModule::DL_Entry object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DL_Entry& x) const;

    /*!
     * @brief Comparison operator.
     * @param x LoggingModule::DL_Entry object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DL_Entry& x) const;

    /*!
     * @brief This function copies the value in member host_id
     * @param _host_id New value to be copied in member host_id
     */
    eProsima_user_DllExport void host_id(
            const std::string& _host_id);

    /*!
     * @brief This function moves the value in member host_id
     * @param _host_id New value to be moved in member host_id
     */
    eProsima_user_DllExport void host_id(
            std::string&& _host_id);

    /*!
     * @brief This function returns a constant reference to member host_id
     * @return Constant reference to member host_id
     */
    eProsima_user_DllExport const std::string& host_id() const;

    /*!
     * @brief This function returns a reference to member host_id
     * @return Reference to member host_id
     */
    eProsima_user_DllExport std::string& host_id();


    /*!
     * @brief This function sets a value in member process_id
     * @param _process_id New value for member process_id
     */
    eProsima_user_DllExport void process_id(
            int32_t _process_id);

    /*!
     * @brief This function returns the value of member process_id
     * @return Value of member process_id
     */
    eProsima_user_DllExport int32_t process_id() const;

    /*!
     * @brief This function returns a reference to member process_id
     * @return Reference to member process_id
     */
    eProsima_user_DllExport int32_t& process_id();


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message();


    /*!
     * @brief This function copies the value in member log_context
     * @param _log_context New value to be copied in member log_context
     */
    eProsima_user_DllExport void log_context(
            const LoggingModule::DL_Context& _log_context);

    /*!
     * @brief This function moves the value in member log_context
     * @param _log_context New value to be moved in member log_context
     */
    eProsima_user_DllExport void log_context(
            LoggingModule::DL_Context&& _log_context);

    /*!
     * @brief This function returns a constant reference to member log_context
     * @return Constant reference to member log_context
     */
    eProsima_user_DllExport const LoggingModule::DL_Context& log_context() const;

    /*!
     * @brief This function returns a reference to member log_context
     * @return Reference to member log_context
     */
    eProsima_user_DllExport LoggingModule::DL_Context& log_context();


    /*!
     * @brief This function sets a value in member kind
     * @param _kind New value for member kind
     */
    eProsima_user_DllExport void kind(
            LoggingModule::DL_Kind _kind);

    /*!
     * @brief This function returns the value of member kind
     * @return Value of member kind
     */
    eProsima_user_DllExport LoggingModule::DL_Kind kind() const;

    /*!
     * @brief This function returns a reference to member kind
     * @return Reference to member kind
     */
    eProsima_user_DllExport LoggingModule::DL_Kind& kind();


    /*!
     * @brief This function copies the value in member timestamp
     * @param _timestamp New value to be copied in member timestamp
     */
    eProsima_user_DllExport void timestamp(
            const std::string& _timestamp);

    /*!
     * @brief This function moves the value in member timestamp
     * @param _timestamp New value to be moved in member timestamp
     */
    eProsima_user_DllExport void timestamp(
            std::string&& _timestamp);

    /*!
     * @brief This function returns a constant reference to member timestamp
     * @return Constant reference to member timestamp
     */
    eProsima_user_DllExport const std::string& timestamp() const;

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport std::string& timestamp();

private:

    std::string m_host_id;
    int32_t m_process_id{0};
    std::string m_message;
    LoggingModule::DL_Context m_log_context;
    LoggingModule::DL_Kind m_kind{LoggingModule::Error};
    std::string m_timestamp;

};

} // namespace LoggingModule

#endif // _FAST_DDS_GENERATED_LOGGINGMODULE_DLOGGER_H_



