// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dlogger.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "dlogger.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace LoggingModule {



DL_Context::DL_Context()
{
}

DL_Context::~DL_Context()
{
}

DL_Context::DL_Context(
        const DL_Context& x)
{
    m_filename = x.m_filename;
    m_line = x.m_line;
    m_function = x.m_function;
    m_category = x.m_category;
}

DL_Context::DL_Context(
        DL_Context&& x) noexcept
{
    m_filename = std::move(x.m_filename);
    m_line = x.m_line;
    m_function = std::move(x.m_function);
    m_category = std::move(x.m_category);
}

DL_Context& DL_Context::operator =(
        const DL_Context& x)
{

    m_filename = x.m_filename;
    m_line = x.m_line;
    m_function = x.m_function;
    m_category = x.m_category;
    return *this;
}

DL_Context& DL_Context::operator =(
        DL_Context&& x) noexcept
{

    m_filename = std::move(x.m_filename);
    m_line = x.m_line;
    m_function = std::move(x.m_function);
    m_category = std::move(x.m_category);
    return *this;
}

bool DL_Context::operator ==(
        const DL_Context& x) const
{
    return (m_filename == x.m_filename &&
           m_line == x.m_line &&
           m_function == x.m_function &&
           m_category == x.m_category);
}

bool DL_Context::operator !=(
        const DL_Context& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member filename
 * @param _filename New value to be copied in member filename
 */
void DL_Context::filename(
        const std::string& _filename)
{
    m_filename = _filename;
}

/*!
 * @brief This function moves the value in member filename
 * @param _filename New value to be moved in member filename
 */
void DL_Context::filename(
        std::string&& _filename)
{
    m_filename = std::move(_filename);
}

/*!
 * @brief This function returns a constant reference to member filename
 * @return Constant reference to member filename
 */
const std::string& DL_Context::filename() const
{
    return m_filename;
}

/*!
 * @brief This function returns a reference to member filename
 * @return Reference to member filename
 */
std::string& DL_Context::filename()
{
    return m_filename;
}


/*!
 * @brief This function sets a value in member line
 * @param _line New value for member line
 */
void DL_Context::line(
        int32_t _line)
{
    m_line = _line;
}

/*!
 * @brief This function returns the value of member line
 * @return Value of member line
 */
int32_t DL_Context::line() const
{
    return m_line;
}

/*!
 * @brief This function returns a reference to member line
 * @return Reference to member line
 */
int32_t& DL_Context::line()
{
    return m_line;
}


/*!
 * @brief This function copies the value in member function
 * @param _function New value to be copied in member function
 */
void DL_Context::function(
        const std::string& _function)
{
    m_function = _function;
}

/*!
 * @brief This function moves the value in member function
 * @param _function New value to be moved in member function
 */
void DL_Context::function(
        std::string&& _function)
{
    m_function = std::move(_function);
}

/*!
 * @brief This function returns a constant reference to member function
 * @return Constant reference to member function
 */
const std::string& DL_Context::function() const
{
    return m_function;
}

/*!
 * @brief This function returns a reference to member function
 * @return Reference to member function
 */
std::string& DL_Context::function()
{
    return m_function;
}


/*!
 * @brief This function copies the value in member category
 * @param _category New value to be copied in member category
 */
void DL_Context::category(
        const std::string& _category)
{
    m_category = _category;
}

/*!
 * @brief This function moves the value in member category
 * @param _category New value to be moved in member category
 */
void DL_Context::category(
        std::string&& _category)
{
    m_category = std::move(_category);
}

/*!
 * @brief This function returns a constant reference to member category
 * @return Constant reference to member category
 */
const std::string& DL_Context::category() const
{
    return m_category;
}

/*!
 * @brief This function returns a reference to member category
 * @return Reference to member category
 */
std::string& DL_Context::category()
{
    return m_category;
}




DL_Entry::DL_Entry()
{
}

DL_Entry::~DL_Entry()
{
}

DL_Entry::DL_Entry(
        const DL_Entry& x)
{
    m_host_id = x.m_host_id;
    m_process_id = x.m_process_id;
    m_message = x.m_message;
    m_log_context = x.m_log_context;
    m_kind = x.m_kind;
    m_timestamp = x.m_timestamp;
}

DL_Entry::DL_Entry(
        DL_Entry&& x) noexcept
{
    m_host_id = std::move(x.m_host_id);
    m_process_id = x.m_process_id;
    m_message = std::move(x.m_message);
    m_log_context = std::move(x.m_log_context);
    m_kind = x.m_kind;
    m_timestamp = std::move(x.m_timestamp);
}

DL_Entry& DL_Entry::operator =(
        const DL_Entry& x)
{

    m_host_id = x.m_host_id;
    m_process_id = x.m_process_id;
    m_message = x.m_message;
    m_log_context = x.m_log_context;
    m_kind = x.m_kind;
    m_timestamp = x.m_timestamp;
    return *this;
}

DL_Entry& DL_Entry::operator =(
        DL_Entry&& x) noexcept
{

    m_host_id = std::move(x.m_host_id);
    m_process_id = x.m_process_id;
    m_message = std::move(x.m_message);
    m_log_context = std::move(x.m_log_context);
    m_kind = x.m_kind;
    m_timestamp = std::move(x.m_timestamp);
    return *this;
}

bool DL_Entry::operator ==(
        const DL_Entry& x) const
{
    return (m_host_id == x.m_host_id &&
           m_process_id == x.m_process_id &&
           m_message == x.m_message &&
           m_log_context == x.m_log_context &&
           m_kind == x.m_kind &&
           m_timestamp == x.m_timestamp);
}

bool DL_Entry::operator !=(
        const DL_Entry& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member host_id
 * @param _host_id New value to be copied in member host_id
 */
void DL_Entry::host_id(
        const std::string& _host_id)
{
    m_host_id = _host_id;
}

/*!
 * @brief This function moves the value in member host_id
 * @param _host_id New value to be moved in member host_id
 */
void DL_Entry::host_id(
        std::string&& _host_id)
{
    m_host_id = std::move(_host_id);
}

/*!
 * @brief This function returns a constant reference to member host_id
 * @return Constant reference to member host_id
 */
const std::string& DL_Entry::host_id() const
{
    return m_host_id;
}

/*!
 * @brief This function returns a reference to member host_id
 * @return Reference to member host_id
 */
std::string& DL_Entry::host_id()
{
    return m_host_id;
}


/*!
 * @brief This function sets a value in member process_id
 * @param _process_id New value for member process_id
 */
void DL_Entry::process_id(
        int32_t _process_id)
{
    m_process_id = _process_id;
}

/*!
 * @brief This function returns the value of member process_id
 * @return Value of member process_id
 */
int32_t DL_Entry::process_id() const
{
    return m_process_id;
}

/*!
 * @brief This function returns a reference to member process_id
 * @return Reference to member process_id
 */
int32_t& DL_Entry::process_id()
{
    return m_process_id;
}


/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void DL_Entry::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void DL_Entry::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& DL_Entry::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& DL_Entry::message()
{
    return m_message;
}


/*!
 * @brief This function copies the value in member log_context
 * @param _log_context New value to be copied in member log_context
 */
void DL_Entry::log_context(
        const LoggingModule::DL_Context& _log_context)
{
    m_log_context = _log_context;
}

/*!
 * @brief This function moves the value in member log_context
 * @param _log_context New value to be moved in member log_context
 */
void DL_Entry::log_context(
        LoggingModule::DL_Context&& _log_context)
{
    m_log_context = std::move(_log_context);
}

/*!
 * @brief This function returns a constant reference to member log_context
 * @return Constant reference to member log_context
 */
const LoggingModule::DL_Context& DL_Entry::log_context() const
{
    return m_log_context;
}

/*!
 * @brief This function returns a reference to member log_context
 * @return Reference to member log_context
 */
LoggingModule::DL_Context& DL_Entry::log_context()
{
    return m_log_context;
}


/*!
 * @brief This function sets a value in member kind
 * @param _kind New value for member kind
 */
void DL_Entry::kind(
        LoggingModule::DL_Kind _kind)
{
    m_kind = _kind;
}

/*!
 * @brief This function returns the value of member kind
 * @return Value of member kind
 */
LoggingModule::DL_Kind DL_Entry::kind() const
{
    return m_kind;
}

/*!
 * @brief This function returns a reference to member kind
 * @return Reference to member kind
 */
LoggingModule::DL_Kind& DL_Entry::kind()
{
    return m_kind;
}


/*!
 * @brief This function copies the value in member timestamp
 * @param _timestamp New value to be copied in member timestamp
 */
void DL_Entry::timestamp(
        const std::string& _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function moves the value in member timestamp
 * @param _timestamp New value to be moved in member timestamp
 */
void DL_Entry::timestamp(
        std::string&& _timestamp)
{
    m_timestamp = std::move(_timestamp);
}

/*!
 * @brief This function returns a constant reference to member timestamp
 * @return Constant reference to member timestamp
 */
const std::string& DL_Entry::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
std::string& DL_Entry::timestamp()
{
    return m_timestamp;
}




} // namespace LoggingModule
// Include auxiliary functions like for serializing/deserializing.
#include "dloggerCdrAux.ipp"

